name: CDN Deployment

on:
  push:
    branches:
      - main
      - cdn-dist
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (leave empty for latest)'
        required: false
        default: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate docs
        run: |
          npm install clean-jsdoc-theme
          npm run docs

      # Sync cdn-dist with main
      - name: Sync cdn-dist with main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git fetch origin cdn-dist
          
          # Check if cdn-dist branch exists remotely
          if git ls-remote --heads origin cdn-dist | grep -q 'cdn-dist'; then
            git checkout -B cdn-dist origin/cdn-dist
            
            # Use --allow-unrelated-histories for initial merge if needed
            git merge origin/main --allow-unrelated-histories -m "Merge main into cdn-dist" || echo "Merge failed, continuing with build"
          else
            # Create new cdn-dist branch
            git checkout --orphan cdn-dist
            git reset --hard
            mkdir -p dist docs
            touch dist/.gitkeep docs/.gitkeep
            git add dist/.gitkeep docs/.gitkeep
            git commit -m "Initial cdn-dist branch"
          fi 

      # Copy build files
      - name: Copy build files to cdn-dist branch
        run: |
          # Make sure we're using the current build artifacts
          cp -rv dist/* dist/ || echo "No dist files to copy"
          cp -rv docs/* docs/ || echo "No docs files to copy"
          
          # Show file sizes for debugging
          echo "Final dist files:"
          du -sh dist/* || echo "No dist files found"
      
      # Commit and push updates
      - name: Commit and push updates
        run: |
          git add dist docs
          git commit -m "Rebuild CDN files and docs for tag ${{ github.ref_name }}" || echo "No changes to commit."
          git push origin cdn-dist

      - name: Update latest tag
        run: |
          git tag -f latest
          git push -f origin latest
