name: CDN Deployment

on:
  push:
    branches:
      - main
      - cdn-dist
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (leave empty for latest)'
        required: false
        default: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate docs
        run: |
          npm install clean-jsdoc-theme
          npm run docs

      # Sync cdn-dist with main
      - name: Sync cdn-dist with main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git fetch origin cdn-dist
          git checkout -B cdn-dist origin/cdn-dist
          git merge origin/main || echo "Already up to date with main" 

      # Commit and push updates
      - name: Commit and push updates
        run: |
          git add dist docs
          git commit -m "Rebuild CDN files and docs for tag ${{ github.ref_name }}" || echo "No changes to commit."
          git pull --rebase origin cdn-dist  # Ensure we have the latest changes
          git push origin cdn-dist

      - name: Update latest tag
        run: |
          git tag -f latest
          git push -f origin latest
