name: Semantic Release

on:
  push:
    branches: [main, master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Generate docs
        run: |
          npm install clean-jsdoc-theme
          npm run docs
        
      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_ACCESS: public
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
          semantic-release
      
      - name: Upload dist to current release tag
        uses: softprops/action-gh-release@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          tag_name: v${{ steps.semantic.outputs.new_release_version }}
          files: |
            dist/gnss.js
            dist/gnss.min.js
            dist/gnss.esm.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Update CDN branch directly
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check out cdn-dist branch
          git fetch origin cdn-dist || git checkout --orphan cdn-dist
          
          if git ls-remote --heads origin cdn-dist | grep -q 'cdn-dist'; then
            git checkout -B cdn-dist origin/cdn-dist
          else
            git checkout --orphan cdn-dist
            git reset --hard
            mkdir -p dist docs
            touch dist/.gitkeep docs/.gitkeep
            git add dist/.gitkeep docs/.gitkeep
            git commit -m "Initial cdn-dist branch"
            git push origin cdn-dist
            git checkout cdn-dist
          fi
          
          # Debug file sizes
          echo "Original dist files:"
          du -sh dist/* || echo "No dist files found"
          
          # Copy build artifacts to cdn-dist branch
          mkdir -p /tmp/dist /tmp/docs
          cp -rv dist/* /tmp/dist/ || echo "No dist files to copy"
          cp -rv docs/* /tmp/docs/ || echo "No docs files to copy"
          
          # Clear files but keep .git
          find . -mindepth 1 -not -path "./.git*" -delete
          
          # Copy files back
          mkdir -p dist docs
          cp -rv /tmp/dist/* dist/ || echo "No dist files to restore"
          cp -rv /tmp/docs/* docs/ || echo "No docs files to restore"
          
          # Debug final files
          echo "Final dist files:"
          du -sh dist/* || echo "No dist files found"
          
          # Commit and push changes
          git add dist docs
          git commit -m "Update CDN files for release v${{ steps.semantic.outputs.new_release_version }}" || echo "No changes to commit"
          git push origin cdn-dist
          
          # Update latest tag
          git tag -f latest
          git push -f origin latest